id: I995A7A59
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-31T05:04:32.667964'
last_modified: '2022-05-31T05:04:32.668041'
parser: null
source_metadata:
  title: Lobzang Chökyi Gyaltsen
  language: en
  description: 'Texts by and about Lobzang Chökyi Gyaltsen (blo bzang chos kyi rgyal
    mtshan, 1570–1662), the first or fourth Paṇchen Lama (depending on the method
    of counting), a prolific author and teacher of the Fifth Dalai Lama:'
  volume:
    f9783:
      title: A Method of Confessing and Pledging through the Four Powers
      base_file: f9783.txt
      order: 1
      parent: Confession
    fB0D9:
      title: Method of Confession based on the Four Powers
      base_file: fB0D9.txt
      order: 2
      parent: Confession
    f454E:
      title: Rays of Moonlight to Dispel the Darkness of Misdeeds
      base_file: f454E.txt
      order: 3
      parent: Confession
    fAF50:
      title: 'Lasel Chenmo: A Sang Offering to the Nāgas'
      base_file: fAF50.txt
      order: 4
      parent: Offering Rites
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
